//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheShop.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheShop.Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is sold..
        /// </summary>
        public static string _is_sold {
            get {
                return ResourceManager.GetString("_is_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article buyer id: {0}.
        /// </summary>
        public static string article_buyer_id__ {
            get {
                return ResourceManager.GetString("article_buyer_id__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article from {0}.
        /// </summary>
        public static string Article_from__ {
            get {
                return ResourceManager.GetString("Article_from__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article ID: {0}.
        /// </summary>
        public static string article_ID__ {
            get {
                return ResourceManager.GetString("article_ID__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article is sold: {0}.
        /// </summary>
        public static string article_is_sold__ {
            get {
                return ResourceManager.GetString("article_is_sold__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article Name: {0}.
        /// </summary>
        public static string article_Name__ {
            get {
                return ResourceManager.GetString("article_Name__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not available.
        /// </summary>
        public static string Article_not_available {
            get {
                return ResourceManager.GetString("Article_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to article Price: {0}.
        /// </summary>
        public static string article_Price__ {
            get {
                return ResourceManager.GetString("article_Price__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article with id=.
        /// </summary>
        public static string Article_with_id {
            get {
                return ResourceManager.GetString("Article_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article with id: {0} is sold..
        /// </summary>
        public static string Article_with_id__is_sold {
            get {
                return ResourceManager.GetString("Article_with_id__is_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not order article.
        /// </summary>
        public static string Could_not_order_article {
            get {
                return ResourceManager.GetString("Could_not_order_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save article with id.
        /// </summary>
        public static string Could_not_save_article_with_id {
            get {
                return ResourceManager.GetString("Could_not_save_article_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug: .
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: .
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info: .
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order successful for article with id: {0}.
        /// </summary>
        public static string Order_successful_for_article_with_id {
            get {
                return ResourceManager.GetString("Order_successful_for_article_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplier1.
        /// </summary>
        public static string supplier1 {
            get {
                return ResourceManager.GetString("supplier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplier2.
        /// </summary>
        public static string supplier2 {
            get {
                return ResourceManager.GetString("supplier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplier3.
        /// </summary>
        public static string supplier3 {
            get {
                return ResourceManager.GetString("supplier3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to order article with id: {0} and max price less than {1}.
        /// </summary>
        public static string Trying_to_order_article_with_id__and_max_price_less_than__ {
            get {
                return ResourceManager.GetString("Trying_to_order_article_with_id__and_max_price_less_than__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to sell article with id: {0}.
        /// </summary>
        public static string Trying_to_sell_article_with_id__ {
            get {
                return ResourceManager.GetString("Trying_to_sell_article_with_id__", resourceCulture);
            }
        }
    }
}
